%calculate pValues from features matrix
function pValues_struct = getpValues(targetArray, pairedDet, singleStar_alpha)
[pValue_bothP,~,~,pValue_multP,allMatrix_P] = ...
    testAnalysis(targetArray, true, pairedDet, singleStar_alpha);
[pValue_bothNP,~,~,pValue_multNP,allMatrix_NP] = ...
    testAnalysis(targetArray, false,pairedDet,  singleStar_alpha);
pValues_struct = struct('bothP', pValue_bothP, 'multP', pValue_multP, ...
    'allP', allMatrix_P, 'bothNP', pValue_bothNP, ...
    'multNP', pValue_multNP, 'allNP', allMatrix_NP);
end
